name: Fetch Daily Giphy Reddit GIF Data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch Giphy Reddit GIF Data
      run: |
        python fetch_giphy_data.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git pull origin main   # Add this line to pull the latest changes
        git add .
        git commit -m "Update Giphy Reddit GIF data $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
