name: Fetch Daily Giphy Reddit GIF Data

on:
  schedule:
    # Runs every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Data Collection Script
        run: python fetch_data.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Giphy Reddit GIF data $(date +'%Y-%m-%d %H:%M:%S')" && git push)
